### ISSUE TITLE
Could not establish connection - v.onDidWriteData is not a function

### ISSUE THREAD

**Issue by dcleblanc** [microsoft/vscode-remote-release#2172]
After updating to 1.41.1, I'm unable to connect to my remote, get the above listed error. Tried reinstalling 1.41, did not revert me to previous version.

**Comment by roblourens** [comment]
Please check that the extension is updated to the latest version

**Comment by dcleblanc** [comment]
I ended up resolving the problem by completely uninstalling it, then installing it fresh. On reinstall, it said I didn’t need that extension any longer, and asked to remove it, which I did. Now it works.
