### ISSUE TITLE
Remote container setup broken after upgrade to 1.38

### ISSUE THREAD

**Issue by tomasaschan** [microsoft/vscode-remote-release#1373]
I just updated to 1.38, and my remote container setup immediately stopped working. It shows the following error toasts:

> Resolving the authority `dev-container` failed

> Failed to connect to the remote extension host server (Error: n.window.createTerminalRenderer is not a function)

It was working flawlessly on the version I had before the update; and I have confirmed that downgrading VS Code to 1.37.1 resolved the issue. I've also deleted all traces of containers and volumes related to this workspace without any effect.

How can I help troubleshooting this?

**Comment by chrmarti** [comment]
You need to upgrade the extension too. (There were some proposed API changes between 1.37 and 1.38 on which the extension depends.)
