### ISSUE TITLE
using the Podman cli leads to "undefined is not a function error"

### ISSUE THREAD

**Issue by fpipita** [microsoft/vscode-remote-release#3307]
Hi and first of all thank you for your awesome work.

Regarding the issue, I'm trying to make the `Remote Containers` extension `v0.122.1` work with `Podman 1.9.3` (`conmon 2.0.18`) on `Fedora 32`.

I've done it by setting the `Remote Containers > Docker Path` option to `podman` first and also by aliasing the `podman` executable to `docker` later, when the first attempt failed.

Basically, in either case, when I access the `Containers` section in the `Remote explorer`, I get an error notification: "undefined is not a function".
Also, I can't see any of my running containers there and can't attach to any of them either.

I've tried to reproduce the steps described above on a clean VSCode installation, with no other extensions installed but the `Remote Containers` one.

Please, let me know whether I should provide any additional information.
Thank you

Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.6.19-300.fc32.x86_64

**Comment by fpipita** [comment]
Hi, I've just updated Podman from v1.9.3 to v2.0.1 without doing any changes to the extension/VSCode config and now everything works fine. 

So, I guess the issue was related to Podman v1.9.3.

**Comment by chrmarti** [comment]
Closing as fixed upstream. Thanks.
